
# Introduction
Social networks such as Facebook, Instagram and Twitter are now integrated into most people's everyday lives. The users of social networks no longer just use them to keep in touch with friends, but increasingly facilitate social networks to search for information. Besides that, they also form an opinion based on the information and contributions available in social networks. While searching for information and integrating it into their opinion formation, users are no longer just passive recipients of information in online social networks, but are also actively spreading their own opinions [@Frees2018; @Hoellig2016; @Li2017]. Thus, the dissemination of new information is increasing and a broader range of opinions is voiced [@Bakshy2012]. 

Social networks play a powerful role and not only influence the formation of opinion of individuals, but can also play a decisive role in political situations and decisions [@Guille2013]. It has been shown in the past, that social networks have a great influence on political decisions. One example for this was the American presidential election 2008, where many people saw a great influence of Twitter at the elections [@hughes2009]. 

While the amount of information users receive has changed through social networks, we also have to consider that information can now be individualized through the individual user's interaction with the network and its structure [@DeVito2017]. 


On the Internet, users can find almost any information they are looking for. However, the amount of information available on the Internet is now so high that users are no longer able to consume all the information. In addition, users also find contradicting information on the Internet. The increasing availability of information on the Internet has led to the development of recommendation systems [@Adomavicius2005]. Aiming to make it easier for users to select information, these systems analyse the information available on the Internet, filter it according to specific criteria and provide users with recommendations tailored to their needs [@Burke2002].  

While this simplifies the search for information on the Internet and in social media for users at first, the selection of information can also have negative consequences. In the past, for example, the number of voices that view social networks negatively increased for the fact that political opinions were deliberately influenced and political results manipulated.%Hier könnte auch noch eine Quelle hin Research is worried about the impact that the use of social networks can have on user behaviour [@Stark2017]. 

Research so far does not tell us much how opinion-forming processes actually take place in social networks and we can't predict them, let alone their consequences. However, it is very important to consider the impact that the use of social networks has on user opinion formation. 

Opinion forming and the processes that influence the formation of opinions have been studied since the 1960s. In the meantime, aspects that were of little or no importance before the rise of the Internet have become relevant for the research of the formation of opinion by individuals. First of all, in social networks every user can express his opinion and reach a large number of other users by just resharing or reposting [@Cheng2014].

By other users reposting the opinion of a user, long cascades are created and the opinion is disseminated [@Cheng2014]. Users share information targeting to convince other users of their opinion. Social media simplyfied that users can convey one's opinion to other individuals

 Nevertheless, one aspect that needs to be considered is that users differ in their sharing habits. Lottridge and Bentley investigated the motivation to share contents and the frequency of sharing news on public, social and private platforms. They differentiate between different types of forwarding. Users can share messages with other users, they can share information in a personal message or share information on a social network or public a content publicly. In their research, they found that users have different intentions with different forms of sharing. Users share information publicly, primarily when they want to contribute an ideology. In contrast, they send private messages primarily to tell stories that correspond to their own interests or the context in which the user finds themselves. The first group, sharing news to all channels. So they share both publicly and socially and privately. In contrast, the second group does not share news at all. The last group shares messages to private and social. In keeping with this, they also found that the group that shared the least posts had a negative attitude toward online discussion, whereas the group that shared the most posts had a neutral attitude toward online discussion [@Lottridge2018a]. 
 
In order to understand how the dissemination of information and thus also the formation of opinion in social networks takes place, it is therefore necessary to first consider what motivates users to express their opinion in social media and which personality traits the users have, that publish their opinion in social media. It is further relevant to look at different network structures, as they can also influence to which users a certain content is spread to friends or other users. 